/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef verbindung_CONSTANTS_H
#define verbindung_CONSTANTS_H

#include "verbindung_types.h"

namespace Thrift {

	class verbindungConstants {
	public:
		verbindungConstants();

	};

	extern const verbindungConstants g_verbindung_constants;

} // namespace

#endif
