/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "verbindung_constants.h"

namespace Thrift {

const verbindungConstants g_verbindung_constants;

verbindungConstants::verbindungConstants() {
}

} // namespace

